server:
    port: 8070

spring:
    application:
        name: eureka-server
    config:
        import: "optional:configserver:"
    cloud:
        config:
            uri: http://configserver:8071
        loadbalancer:
            ribbon:
                enabled: false
